"""initial_schema

Revision ID: cf1f56210add
Revises: 
Create Date: 2026-09-12 10:50:13.064873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1f56210add'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('olts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_olts_name'), ['name'], unique=True)

    op.create_table('onus_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=True),
    sa.Column('subscriber_name', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('from_olt_id', sa.String(length=36), nullable=True),
    sa.Column('from_olt_name', sa.String(length=64), nullable=True),
    sa.Column('from_port', sa.String(length=32), nullable=True),
    sa.Column('from_onu_id', sa.Integer(), nullable=True),
    sa.Column('from_circuit_id', sa.String(length=128), nullable=True),
    sa.Column('to_olt_id', sa.String(length=36), nullable=True),
    sa.Column('to_olt_name', sa.String(length=64), nullable=True),
    sa.Column('to_port', sa.String(length=32), nullable=True),
    sa.Column('to_onu_id', sa.Integer(), nullable=True),
    sa.Column('to_circuit_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onus_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onus_history_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_onus_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backups_metadata',
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.Column('olt_id', sa.String(length=36), nullable=False),
    sa.Column('olt_name', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backup_id')
    )
    with op.batch_alter_table('backups_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_metadata_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backups_metadata_olt_id'), ['olt_id'], unique=False)

    op.create_table('onus_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=True),
    sa.Column('subscriber_name', sa.String(length=128), nullable=True),
    sa.Column('contract_status', sa.String(length=32), nullable=False),
    sa.Column('current_olt_id', sa.String(length=36), nullable=True),
    sa.Column('current_port', sa.String(length=32), nullable=True),
    sa.Column('current_onu_id', sa.Integer(), nullable=True),
    sa.Column('circuit_id', sa.String(length=128), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_olt_id'], ['olts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onus_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onus_inventory_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onus_inventory_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onus_inventory_contract_status'), ['contract_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onus_inventory_current_olt_id'), ['current_olt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onus_inventory_serial'), ['serial'], unique=True)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_subscription_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('onus_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onus_inventory_serial'))
        batch_op.drop_index(batch_op.f('ix_onus_inventory_current_olt_id'))
        batch_op.drop_index(batch_op.f('ix_onus_inventory_contract_status'))
        batch_op.drop_index(batch_op.f('ix_onus_inventory_contract_id'))
        batch_op.drop_index(batch_op.f('ix_onus_inventory_circuit_id'))

    op.drop_table('onus_inventory')
    with op.batch_alter_table('backups_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_metadata_olt_id'))
        batch_op.drop_index(batch_op.f('ix_backups_metadata_created_at'))

    op.drop_table('backups_metadata')
    op.drop_table('webhook_subscriptions')
    with op.batch_alter_table('onus_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onus_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_onus_history_serial'))

    op.drop_table('onus_history')
    with op.batch_alter_table('olts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_olts_name'))

    op.drop_table('olts')
    # ### end Alembic commands ###
