import json
from unittest.mock import MagicMock, patch
import pytest
from fastapi.testclient import TestClient

from app.core.webhook_signer import verify_signature
from app.models.provision import ProvisionResponse, ONUActionResponse


def test_create_webhook_with_autogenerated_secret(client: TestClient, auth_headers):
    payload = {
        "url": "https://erp.provedor.com.br/api/v1/webhooks/oltapi",
        "description": "ERP IXC Soft Matriz",
        "events": ["onu.reconciled", "onu.detected"],
    }
    response = client.post("/api/v1/webhooks", json=payload, headers=auth_headers)
    assert response.status_code == 201
    data = response.json()

    assert data["url"] == "https://erp.provedor.com.br/api/v1/webhooks/oltapi"
    assert data["description"] == "ERP IXC Soft Matriz"
    assert data["events"] == ["onu.reconciled", "onu.detected"]
    assert data["secret"].startswith("whsec_")
    assert "Location" in response.headers
    assert response.headers["Location"] == f"/api/v1/webhooks/{data['id']}"
    assert "_links" in data
    assert "ping" in data["_links"]


def test_list_webhooks(client: TestClient, auth_headers):
    response = client.get("/api/v1/webhooks", headers=auth_headers)
    assert response.status_code == 200
    items = response.json()
    assert isinstance(items, list)
    assert len(items) >= 1
    assert "_links" in items[0]


def test_get_and_delete_webhook(client: TestClient, auth_headers):
    # Cria webhook
    create_resp = client.post(
        "/api/v1/webhooks",
        json={"url": "https://erp.temp.com/hook", "description": "Temp Hook"},
        headers=auth_headers,
    )
    sub_id = create_resp.json()["id"]

    # Consulta
    get_resp = client.get(f"/api/v1/webhooks/{sub_id}", headers=auth_headers)
    assert get_resp.status_code == 200
    assert get_resp.json()["id"] == sub_id

    # Deleta
    del_resp = client.delete(f"/api/v1/webhooks/{sub_id}", headers=auth_headers)
    assert del_resp.status_code == 204

    # Consulta pós-deleção retorna 404
    get_after = client.get(f"/api/v1/webhooks/{sub_id}", headers=auth_headers)
    assert get_after.status_code == 404


@patch("app.services.webhook_dispatcher.httpx.Client")
def test_ping_webhook(mock_client_class, client: TestClient, auth_headers):
    # Mock do retorno HTTP do ERP
    mock_client = MagicMock()
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.text = "OK"
    mock_client.post.return_value = mock_resp
    mock_client_class.return_value.__enter__.return_value = mock_client

    # Cria webhook
    create_resp = client.post(
        "/api/v1/webhooks",
        json={"url": "https://erp.provedor.com.br/hooks", "secret": "whsec_custom_secret_123"},
        headers=auth_headers,
    )
    assert create_resp.status_code == 201
    sub = create_resp.json()

    # Dispara ping
    ping_resp = client.post(f"/api/v1/webhooks/{sub['id']}/ping", headers=auth_headers)
    assert ping_resp.status_code == 200
    delivery = ping_resp.json()

    assert delivery["success"] is True
    assert delivery["status_code"] == 200
    assert delivery["event"] == "webhook.ping"

    # Valida parâmetros da chamada HTTP feita ao ERP
    assert mock_client.post.called
    call_args = mock_client.post.call_args
    url = call_args[0][0]
    headers = call_args[1]["headers"]
    raw_content = call_args[1]["content"]

    assert url == "https://erp.provedor.com.br/hooks"
    assert headers["X-OLTAPI-Event"] == "webhook.ping"
    assert "X-OLTAPI-Signature" in headers
    assert "X-OLTAPI-Delivery" in headers

    # Valida criptografia da assinatura HMAC SHA-256
    assert verify_signature("whsec_custom_secret_123", raw_content, headers["X-OLTAPI-Signature"]) is True


@patch("app.services.webhook_dispatcher.httpx.Client")
@patch("app.drivers.factory.DriverFactory.get_driver")
def test_reconcile_dispatches_onu_reconciled_webhook(mock_get_driver, mock_client_class, client: TestClient, auth_headers, sample_olt_8820):
    """
    Cenário Completo:
    1. Cadastra webhook com evento 'onu.reconciled'.
    2. Cadastra ONU no inventário.
    3. Simula evento de campo (autofind em outra porta).
    4. Verifica se o OLTAPI auto-recuperou a ONU E disparou o webhook HMAC para o ERP com o novo Circuit ID TR-101.
    """
    # Mock do retorno HTTP do ERP
    mock_client = MagicMock()
    mock_erp_resp = MagicMock()
    mock_erp_resp.status_code = 200
    mock_erp_resp.text = '{"status":"received"}'
    mock_client.post.return_value = mock_erp_resp
    mock_client_class.return_value.__enter__.return_value = mock_client

    # Mock do driver da OLT
    mock_driver = MagicMock()
    mock_driver.provision_onu.return_value = ProvisionResponse(
        success=True,
        olt_id=str(sample_olt_8820.id),
        serial="INCL55443322",
        port="1/4",
        onu_id=12,
        vlan=200,
        message="Provisionado",
    )
    mock_driver.deprovision_onu.return_value = ONUActionResponse(
        success=True,
        action="deprovision",
        olt_id=str(sample_olt_8820.id),
        serial="INCL55443322",
        port="1/1",
        onu_id=2,
        message="Desprovisionado da porta antiga",
    )
    mock_get_driver.return_value = mock_driver

    # 1. Cadastra webhook no OLTAPI
    secret = "whsec_erp_shared_secret_9988"
    wh_payload = {
        "url": "https://erp.provedor.com.br/api/webhooks/oltapi",
        "secret": secret,
        "events": ["onu.reconciled"],
        "description": "Sincronização em tempo real de Circuit ID com o ERP",
    }
    wh_resp = client.post("/api/v1/webhooks", json=wh_payload, headers=auth_headers)
    assert wh_resp.status_code == 201
    assert wh_resp.status_code == 201

    # 2. Cadastra ONU ativa no inventário
    onu_payload = {
        "serial": "INCL55443322",
        "contract_id": "CTR-99001",
        "subscriber_name": "Assinante Fibra Real",
        "contract_status": "ACTIVE",
        "current_olt_id": str(sample_olt_8820.id),
        "current_port": "1/1",
        "current_onu_id": 2,
        "vlan": 200,
        "profile": "DEFAULT",
    }
    onu_resp = client.post("/api/v1/onus", json=onu_payload, headers=auth_headers)
    assert onu_resp.status_code == 201

    # 3. Dispara reconciliação de campo (mudança de porta 1/1 para 1/4)
    reconcile_payload = {
        "serial": "INCL55443322",
        "detected_olt_id": str(sample_olt_8820.id),
        "detected_port": "1/4",
        "detected_onu_id": 12,
        "reason": "Fusão invertida corrigida no campo",
    }
    rec_resp = client.post("/api/v1/onus/reconcile-field-event", json=reconcile_payload, headers=auth_headers)
    assert rec_resp.status_code == 200
    rec_data = rec_resp.json()
    assert rec_data["success"] is True

    # 4. Verifica se o Webhook para o ERP foi disparado
    assert mock_client.post.called
    call_args = mock_client.post.call_args
    headers = call_args[1]["headers"]
    raw_content = call_args[1]["content"]

    assert headers["X-OLTAPI-Event"] == "onu.reconciled"
    assert verify_signature(secret, raw_content, headers["X-OLTAPI-Signature"]) is True

    # Verifica os dados enviados ao ERP
    event_payload = json.loads(raw_content.decode("utf-8"))
    assert event_payload["event"] == "onu.reconciled"
    data = event_payload["data"]
    assert data["serial"] == "INCL55443322"
    assert data["contract_id"] == "CTR-99001"
    assert data["new_port"] == "1/4"
    assert data["new_onu_id"] == 12
    assert data["new_circuit_id"] == f"{sample_olt_8820.name} eth 1/4:12:200"


def test_list_deliveries_endpoint(client: TestClient, auth_headers):
    resp = client.get("/api/v1/webhooks/deliveries", headers=auth_headers)
    assert resp.status_code == 200
    deliveries = resp.json()
    assert isinstance(deliveries, list)
    assert len(deliveries) >= 1  # Devem existir os logs dos testes anteriores
    delivery = deliveries[0]
    assert "subscription_id" in delivery
    assert "event" in delivery
    assert "status_code" in delivery
    assert "duration_ms" in delivery
